# Generated by Django 6.0.7 on 2026-08-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=50)),
                ('ela_score', models.FloatField(help_text='Error Level Analysis residual score (0.0 - 1.0)')),
                ('lineage_match', models.BooleanField(default=False, help_text='True if matching visual vector in Qdrant ledger')),
                ('embedding_valid', models.BooleanField(default=True, help_text='False if zero-vector sentinel fallback triggered')),
                ('search_failed', models.BooleanField(default=False, help_text='True if DuckDuckGo search failed or timed out')),
                ('duration_sec', models.FloatField(help_text='Analysis runtime in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis Audit Log',
                'verbose_name_plural': 'Analysis Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('capture_date', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('media_type', models.CharField(default='image', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ledger Reference Record',
                'verbose_name_plural': 'Ledger Reference Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
